[tool.black]
line-length = 89
exclude = '''
(
  /(
      \.eggs
    | \.git
    | \.mypy_cache
    | \.tox
    | .venv
    | venv
    | build
    | dist
    | tests
    | test_data
  )/
)
'''

[tool.isort]
use_parentheses = "True"
line_length = 89
skip = "build,.tox,venv,tests,test_data"
profile = "black"