# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  TEST_DIR: ./tests
  LINT_DIR: ./source

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y libgl1-mesa-glx libjpegturbo-dev
        python -m pip install --upgrade pip
        if [ -f requirements.dev.txt]; then pip install -r requirements.dev.txt; fi
